trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1 (9c34b185-c933-4327-b21e-543b6e8c06de)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      docker build -t k8sconatinerregistry.azurecr.io/web-game:tag 2048-game
      az acr login -n k8sconatinerregistry
      docker push k8sconatinerregistry.azurecr.io/web-game:tag

- script: cat 01_kubernetes_aks/app-deploy.yaml

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Azure subscription 1 (9c34b185-c933-4327-b21e-543b6e8c06de)'
    azureResourceGroup: 'k8s'
    kubernetesCluster: 'k8scluster'
    useClusterAdmin: true
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: '01_kubernetes_aks'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'Azure subscription 1 (9c34b185-c933-4327-b21e-543b6e8c06de)'
    azureContainerRegistry: 'k8sconatinerregistry.azurecr.io'
    forceUpdate: false